### ISSUE TITLE
Não é possível buildar o projeto. Erro ...JSON.parse

### ISSUE THREAD

**Issue by teles** [galileo-seo-assistant/galileo-seo-assistant#4]
Ao tentar rodar `npm run build` em uma máquina diferente recebo o seguinte erro:

![captura de tela 2018-03-12 as 11 20 36](https://user-images.githubusercontent.com/762639/37289763-375650a6-25e9-11e8-9046-562cc47af69b.png)

Provavelmente existe uma versão mínima do node para o projeto. Se for o caso é necessário deixar isso explícito no README.md.

@taciogt é esse erro que acontece com você?

**Comment by taciogt** [comment]
Esse mesmo erro, @teles

**Comment by teles** [comment]
Vou investigar.
Acho que é só por causa da versão do node.

O problema já era reportado aqui no boilerplate que usei https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate/issues/28

**Comment by teles** [comment]
Basta atualizar a versão do node para 8.qualquer-coisa.
Só não sei se essa versão tem compatilidade com as versões anteriores do node.

**Comment by dann95** [comment]
![image](https://user-images.githubusercontent.com/9970959/37295597-53ac96d0-25f7-11e8-871d-cd64a10c366f.png)
![image](https://user-images.githubusercontent.com/9970959/37295614-6162a2e2-25f7-11e8-8a01-b88df2a696f9.png)

**Comment by dann95** [comment]
@teles Estranho, o spread operator diz ser compativel com a versão http://node.green/#ES2015-syntax-spread-------operator

**Comment by teles** [comment]
Também achei isso estranho @dann95, spread operator era pra ter compatibilidade faz tempo.

**Comment by dann95** [comment]
@teles Ao parecer o spread operator só funciona com Arrays nas versões anteriores do node, pra contornar esse erro, daria pra somar os dois objetos, pois o que ele está fazendo ali é somar dois objetos (como mostra a foto)
![image](https://user-images.githubusercontent.com/9970959/37296372-91995abc-25f9-11e8-99db-0894945578cd.png)

A solução trivial pode ser com Object.assign()
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

**Comment by dann95** [comment]
@teles Sua intenção é dar suporte a maior quantidade de versões do Node possíveis?

**Comment by teles** [comment]
@dann95 sim, prefiro dar mais suporte se possível.

**Comment by teles** [comment]
Beleza @dann95

**Comment by teles** [comment]
Oi, @taciogt. 
Pode fazer um pull e ver se consegue rodar o projeto?
Eu consegui aqui e se você também conseguir damos a issue por fechada.

**Comment by dann95** [comment]
@teles pra evitar que isso acidentalmente aconteça, https://travis-ci.org/

**Comment by teles** [comment]
O problema está resolvido.
Obrigado @dann95 

Vou adicionar o travis como parte do roadmap. :D

**Comment by dann95** [comment]
Se quiser, posso fazer o pr, existe algum slack ou whatsapp para debater sobre esse projeto?
